version: '3.3'

services:

    mariadb:
        container_name: mariadb
        networks:
        - inception
        build: 
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
        volumes:
        - mariadb:/var/lib/mysql
        restart: on-failure
        expose:
        - "3306"
        secrets:
        - db_root_password
        - db_password
        image: mariadb

    nginx:
        container_name: nginx
        volumes:
        - wordpress:/var/www/wordpress
        networks:
        - inception
        depends_on:
        - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
        env_file: .env
        ports:
        - "443:443"
        restart: on-failure
        extra_hosts:
        - "${DOMAIN_NAME}:127.0.0.1"
        - "www.${DOMAIN_NAME}:127.0.0.1"
        image: nginx

    wordpress:
        container_name: wordpress
        env_file: .env
        volumes:
        - wordpress:/var/www/wordpress
        networks:
        - inception
        depends_on:
        - mariadb
        restart: on-failure
        expose: 
        - "9000"
        build: 
            context: requirements/wordpress
            dockerfile: Dockerfile
        secrets:
        - db_root_password
        - db_password
        - wp_admin_password
        - wp_user_password
        image: wordpress

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/${LOGIN}/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '/home/${LOGIN}/data/mariadb'

networks:
    inception:
        driver: bridge

secrets:
    credentials:
        file: ../secrets/credentials.txt
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    wp_admin_password:
        file: ../secrets/wp_admin_password.txt
    wp_user_password:
        file: ../secrets/wp_user_password.txt