apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mariadb:3306
    user: ${MYSQL_USER}
    jsonData:
      database: ${MYSQL_DATABASE}
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: null
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    version: 1
    url: redis:6379
